### ISSUE TITLE
Multiple warnings on start: QMetaObject::connectSlotsByName: No matching signal for...

### ISSUE THREAD

**Issue by SolarBear** [afri-bit/conan-guide#4]
I cloned the project and then performed a `pip install -r requirements.txt && pip install . && conan-guide`.

A few of these warnings are displayed when launching the program. However, the app seems to work just fine afterwards, AFAIK.

Platform: Windows 10 Workstation (Version	10.0.16299 Build 16299)
Python version: 3.9.6 64 bits

```
QMetaObject::connectSlotsByName: No matching signal for on_command_start(QString)
QMetaObject::connectSlotsByName: No matching signal for on_command_result(QString)
QMetaObject::connectSlotsByName: No matching signal for on_command_error(QString)
QMetaObject::connectSlotsByName: No matching signal for on_command_finished(PyObject)
QMetaObject::connectSlotsByName: No matching signal for on_command_progress(QString)
```

**Comment by afri-bit** [comment]
Hi,

thanks for your issue report.
The issue has been fixed in the `develop` branch, this warning messages occured due to slot annotation that are assigned to non native Qt slot methods.

Btw, you can also install the application using `pip`, check out this link https://pypi.org/project/conan-guide/ ;)

I hope I can release the next version soon ;)
